openapi: 3.0.0
servers:
  - url: http://localhost:8090/
    description: Local server
info:
  description: A REST API for money transfers between accounts.
  version: "1.0.0"
  title: Internal Transfers API
  contact:
    email: test@mailinator.com
tags:
  - name: admin
    description: Admin Operations
  - name: user
    description: User Operations
paths:
  /accounts:
    get:
      tags:
        - admin
      summary: list accounts
      operationId: accounts
      description: |
        Returns all the accounts available along with their balance
      responses:
        '200':
          description: array of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '400':
          description: bad input parameter
    post:
      tags:
        - admin
      summary: creates an account
      operationId: createAccount
      description: Creates an Account
      responses:
        '201':
          description: account created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: 'invalid input, balance must not be null'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
        description: Account Creation Request

  /internal/transfer:
    post:
      tags:
        - user
      summary: Transfer Money
      description: |
        Transfer money from one account to another
      operationId: processTransaction
      responses:
        '200':
          description: transfer successful
        '400':
          description: 'invalid input, insufficient balance, transfer to own account not possible, transfer amount must be greater than 0'
        '404':
          description: 'account not found'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InternalTransferRequest'
        description: Internal Transfer Request

components:
  schemas:
    Account:
      type: object
      required:
        - id
        - balance
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        balance:
          type: number
          format: bigdecimal
          example: 605.83
    AccountRequest:
      type: object
      required:
        - balance
      properties:
        balance:
          type: number
          format: bigdecimal
          example: 605.83
    InternalTransferRequest:
      type: object
      required:
        - senderAccountId
        - receiverAccountId
        - amount
      properties:
        senderAccountId:
          type: string
          format: uuid
          example: 833fb7f0-9549-4dbd-b570-2d9e4be2b0ef
        receiverAccountId:
          type: string
          format: uuid
          example: 3c8754aa-6fbe-4b72-ad08-dcbf29501ea3
        amount:
          type: number
          format: bigdecimal
          example: 12.24